### ISSUE TITLE
Improper values

### ISSUE THREAD

**Issue by IvanPr** [bradyvercher/gravity-forms-iframe#32]
The add-on is absolutely great. There is a small bug however.
When the Gravity Form is opened inside a pop-up iframe, the addon provides proper {embed_url} values but improper {embed_post:ID} and {embed_post:post_title} values.

In my case the {embed_post:ID} is equal to the ID of the latest blog post nomatter where the iframe form was filled from...

Thank you.

**Comment by bradyvercher** [comment]
When a form is displayed via an iframe, it's not aware of the parent window. That being the case, it won't be able to set those values, especially since the iframe may embedded on an external site that's not even running WordPress.

If you're embedding a form on the same site that Gravity Forms is installed on, you're better off using the shortcode.

**Comment by IvanPr** [comment]
The shortcode forces the form [plus captcha] load with the page.

The iFrame pop-up loads the form only on request getting proper {embed_url} value.

p.s. If the form is 'not aware of the parent windows' the gravity-forms-iframe add-on should pass empty values for  {embed_post:ID} and {embed_post:post_title}.
